######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 8 00:20:09 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dlinklist.h qt1.h \
    camera.h \
    yuv2rgb.h \
    ui_qt1.h \
    mainwindow.h
FORMS += qt1.ui \
    mainwindow.ui
SOURCES += main.cpp qt1.cpp \
    camera.cpp \
    yuv2rgb.cpp \
    mainwindow.cpp
